// Recover each operator's meaning and fixity from package sources.
//
// Hackage's rendered documentation is generated by Haddock from `-- |`
// comments and `infixl/infixr/infix n op` declarations in the source, so
// reading those out of the defining package's tarball gives us the same
// text the Hackage docs show. Packages are searched in preference order
// (core packages like base/ghc-prim first, then the corpus by popularity);
// the first definition carrying a Haddock comment wins.

import { walkHsFiles } from './count.js';

const FIXITY_RE = /^\s*infix([lr]?)\s+([0-9])\s+(.+?)\s*$/;
const MODULE_RE = /^module\s+([A-Z][A-Za-z0-9_.']*)/m;

// `(<$>) :: ...`, `(==), (/=) :: ...`, `div :: ...` — possibly indented
// (class methods), names before the first `::`.
const SIG_RE =
  /^(\s*)((?:\([^)]*\)|[a-z_][A-Za-z0-9_']*)(?:\s*,\s*(?:\([^)]*\)|[a-z_][A-Za-z0-9_']*))*)\s*::(.*)$/;

// A few primitives have no harvestable signature: `:` is built-in syntax
// (GHC.Types defines the `data`, not a signature) and `seq` is wired into
// the compiler (GHC.Prim has no source on Hackage). Descriptions follow
// their GHC documentation.
const BUILTIN_DOCS = new Map([
  [':', {
    doc: {
      sig: '(:) :: a -> [a] -> [a]',
      text: 'The list constructor: prepends an element to a list (cons).',
      pkg: 'ghc-prim',
      module: 'GHC.Types',
    },
    fixity: { assoc: 'infixr', prec: 5, pkg: 'ghc-prim' },
  }],
  ['seq', {
    doc: {
      sig: 'seq :: a -> b -> b',
      text: 'Evaluates its first argument to weak head normal form, and then returns its second argument as the result.',
      pkg: 'ghc-prim',
      module: 'GHC.Prim',
    },
    fixity: { assoc: 'infixr', prec: 0, pkg: 'ghc-prim' },
  }],
]);

const PRAGMA_LINE_RE = /^\s*\{-#.*#-\}\s*$/;

function sigNames(namesPart) {
  return namesPart
    .split(',')
    .map((s) => s.trim())
    .map((s) => (s.startsWith('(') ? s.slice(1, -1).trim() : s))
    .filter(Boolean);
}

/**
 * Strips Haddock markup down to plain text, first paragraph only.
 * Takes lines with the comment markers already removed.
 */
function cleanDocText(rawLines) {
  const parts = [];
  for (const line of rawLines) {
    const body = line.trim();
    // Code/doctest lines aren't prose: skip leading ones (some docs open
    // with an example), and stop at trailing ones.
    if (body.startsWith('>')) {
      if (parts.length > 0) break;
      continue;
    }
    if (parts.length > 0 && body === '') break; // paragraph break
    if (body !== '') parts.push(body);
  }
  let text = parts.join(' ').replace(/\s+/g, ' ');
  text = text
    .replace(/\\\((.*?)\\\)/g, (_, m) =>
      m.replace(/\\[a-zA-Z]+\{([^{}]*)\}/g, '$1').replace(/\\/g, ''),
    ) // inline LaTeX: \(\mathcal{O}(\min(m,n))\) -> O(min(m,n))
    .replace(/\\"/g, '"')
    .replace(/\[[tv]?'([A-Za-z_][\w.'#]*)'\]/g, '$1')
    .replace(/\b[tv]'([A-Za-z_][\w.'#]*)'/g, '$1')
    .replace(/'(\([!#$%&*+./<>=?@\\^|~:-]+\))'/g, '`$1`')
    .replace(/'([!#$%&*+./<>=?@\\^|~:-]+)'/g, '`$1`')
    .replace(/'([A-Za-z_(][\w.'#)]*)'/g, '$1')
    .replace(/@([^@\n]+)@/g, (_, m) => `\`${m.replace(/`/g, '')}\``)
    .replace(/"([A-Z][A-Za-z0-9_.]*)"/g, '$1')
    .replace(/__([^_]+)__/g, '$1')
    .replace(/(^|\s)\/([^/\n]+)\/(?=[\s,.;:)]|$)/g, '$1$2');

  // Keep whole sentences up to a budget.
  const sentences = text.split(/(?<=[.!?])\s+(?=[A-Z`('"])/);
  let out = '';
  for (const s of sentences) {
    if (out && (out + ' ' + s).length > 180) break;
    out = out ? `${out} ${s}` : s;
  }
  if (out.length > 240) out = `${out.slice(0, 237)}...`;
  // Paragraph breaks can leave dangling lead-ins ("..., i.e.," before a code
  // example, or a sentence ending in ":"); trim those.
  out = out.replace(/,\s*(?:i\.e\.|e\.g\.)\s*,?\s*$/, '.');
  if (out.endsWith(':')) out = out.replace(/\.\s+[^.]*:$/, '.');
  return out;
}

/**
 * The Haddock comment above `lines[sigIdx]`, or undefined. Haddock allows
 * blank lines and pragmas (`{-# INLINE f #-}`) between the comment and the
 * declaration it documents, and the comment may be a `-- |` line block or a
 * `{- | ... -}` block comment.
 */
function haddockAbove(lines, sigIdx) {
  let i = sigIdx - 1;
  while (i >= 0 && (lines[i].trim() === '' || PRAGMA_LINE_RE.test(lines[i]))) i -= 1;
  if (i < 0) return undefined;

  if (/-\}\s*$/.test(lines[i])) {
    // Block comment: find its opener, which must be the Haddock `{- |` form.
    for (let j = i; j >= 0 && j > i - 120; j -= 1) {
      const at = lines[j].indexOf('{-');
      if (at === -1) continue;
      if (!/^\{-\s*[|^]/.test(lines[j].slice(at))) return undefined;
      const raw = lines.slice(j, i + 1).map((l) => l.replace(/-\}\s*$/, ''));
      raw[0] = raw[0].slice(at).replace(/^\{-\s*[|^] ?/, '');
      return cleanDocText(raw);
    }
    return undefined;
  }

  // Line-comment block, possibly interrupted by pragma lines.
  const block = [];
  for (; i >= 0; i -= 1) {
    if (PRAGMA_LINE_RE.test(lines[i])) continue;
    if (!/^\s*--/.test(lines[i])) break;
    block.unshift(lines[i]);
  }
  while (block.length && !/^\s*-- ?\|/.test(block[0])) block.shift();
  if (!block.length) return undefined;
  return cleanDocText(block.map((l) => l.replace(/^\s*--(?: ?[|^])? ?/, '')));
}

/**
 * Fallback for class methods without their own Haddock comment (`==`, `<`,
 * `+`, ... mostly have class-level docs only): if the signature is indented
 * and the nearest less-indented declaration above is a `class`, borrow the
 * class's doc. Returns `{ text, className }` or undefined.
 */
function classDocAbove(lines, sigIdx, indentLen) {
  if (indentLen === 0) return undefined;
  for (let i = sigIdx - 1; i >= 0; i -= 1) {
    const line = lines[i];
    if (line.trim() === '' || /^\s*--/.test(line)) continue;
    const indent = /^(\s*)\S/.exec(line)[1].length;
    if (indent >= indentLen) continue;
    const m = /^\s*class\b(?:.*=>)?\s*([A-Z][A-Za-z0-9_']*)/.exec(line);
    if (!m) return undefined;
    const text = haddockAbove(lines, i);
    return text ? { text: `(method of class ${m[1]}) ${text}`, className: m[1] } : undefined;
  }
  return undefined;
}

/** The signature starting at `lines[sigIdx]`, joined across continuations. */
function fullSignature(lines, sigIdx, indent) {
  const parts = [lines[sigIdx].trim()];
  for (let i = sigIdx + 1; i < Math.min(sigIdx + 6, lines.length); i += 1) {
    const line = lines[i];
    const m = /^(\s*)\S/.exec(line);
    if (!m || m[1].length <= indent.length || /^\s*--/.test(line)) break;
    parts.push(line.trim());
  }
  let sig = parts.join(' ').replace(/\s+/g, ' ');
  if (sig.length > 110) sig = `${sig.slice(0, 107)}...`;
  return sig;
}

// Modules of worked examples and tests define homonyms of the operators
// they demonstrate; never prefer those definitions over library ones.
const EXAMPLE_MODULE_RE = /(^|\.)(Examples?|Documentation|Tutorial|Demo|Tests?)(\.|$)/;

/**
 * Picks one definition for a name out of `candidates`. Preference:
 *
 * 1. For operators concentrated in a few packages (a DSL's `.==`, a pretty
 *    printer's `<+>`), the definition from the corpus package that accounts
 *    for the largest share of the uses — that's the meaning the count is
 *    actually measuring.
 * 2. Otherwise (ubiquitous operators like `<>`), the canonical definition
 *    from the doc-package list, in list order, best-documented first.
 * 3. Any other definition, example modules last.
 */
function chooseCandidate(candidates, byPkg, total, corpusSize, docPkgOrder) {
  const normal = candidates.filter((c) => !EXAMPLE_MODULE_RE.test(c.module));
  const fromDocPkgs = normal
    .filter((c) => docPkgOrder.has(c.pkg))
    .sort((a, b) => b.quality - a.quality || docPkgOrder.get(a.pkg) - docPkgOrder.get(b.pkg));
  const fromCorpus = normal
    .filter((c) => !docPkgOrder.has(c.pkg))
    .map((c) => ({ ...c, share: (byPkg?.get(c.pkg) ?? 0) / (total || 1) }))
    .sort((a, b) => b.share - a.share || b.quality - a.quality);

  // A documented corpus definition wins on a modest share; an undocumented
  // one (bare signature) only when the operator is essentially that
  // package's alone — otherwise a documented canonical homonym reads better.
  const concentrated = (byPkg?.size ?? 0) <= corpusSize / 3;
  if (concentrated && fromCorpus.length) {
    const best = fromCorpus.find((c) => c.quality >= 1 && c.share >= 0.2) ?? fromCorpus[0];
    if ((best.quality >= 1 && best.share >= 0.2) || best.share >= 0.75) return best;
  }
  return (
    fromDocPkgs[0] ??
    fromCorpus[0] ??
    candidates.slice().sort((a, b) => b.quality - a.quality)[0]
  );
}

/**
 * Searches `packages` for the definitions of the `wanted` names. `usage`
 * maps each name to its per-package use counts (to resolve homonyms) and
 * `docPkgNames` lists the canonical doc packages in preference order.
 * Returns a Map from name to
 * `{ doc: { sig, text, pkg, module }?, fixity: { assoc, prec, pkg }?, fixityVaries }`.
 */
export function harvestDocs(
  wanted,
  packages,
  { usage, docPkgNames = [], corpusSize = 1, maxFileBytes, log = () => {} } = {},
) {
  const results = new Map();
  for (const name of wanted) {
    results.set(name, { candidates: new Map(), fixity: undefined, allFixities: [] });
  }
  const stats = { skippedTestDirs: 0, skippedLiterate: 0, skippedLarge: 0 };

  for (const pkg of packages) {
    for (const file of walkHsFiles(pkg.dir, { includeTests: false, maxFileBytes, stats })) {
      // Cheap prefilter: most files define none of the wanted names.
      if (!file.text.includes('::') && !file.text.includes('infix')) continue;
      const lines = file.text.split('\n');
      let moduleName;

      for (let i = 0; i < lines.length; i += 1) {
        const line = lines[i];

        // Fixity declarations may carry a trailing line comment
        // (`infixl 9 !,!? --`); strip it, but keep operators like `--|`.
        const fix = FIXITY_RE.exec(line.replace(/\s--(\s.*)?$/, ''));
        if (fix) {
          const assoc = `infix${fix[1]}`;
          const prec = Number(fix[2]);
          for (let op of fix[3].split(',')) {
            op = op.trim().replace(/^`(.*)`$/, '$1');
            const r = results.get(op);
            if (!r) continue;
            r.allFixities.push({ assoc, prec, pkg: pkg.name });
            if (!r.fixity) r.fixity = { assoc, prec, pkg: pkg.name };
          }
          continue;
        }

        if (!line.includes('::')) continue;
        const sig = SIG_RE.exec(line);
        if (!sig) continue;
        for (const defined of sigNames(sig[2])) {
          const r = results.get(defined);
          if (!r) continue;
          // One candidate per package: its best-documented definition (own
          // Haddock comment beats the class's doc beats a bare signature);
          // at equal quality, the one from the shallower module path
          // (GHC.Internal.List's `lookup`, not GHC.Internal.Event.PSQ's).
          const existing = r.candidates.get(pkg.name);
          let text = haddockAbove(lines, i);
          let quality = 2;
          if (!text) {
            text = classDocAbove(lines, i, sig[1].length)?.text;
            quality = text ? 1 : 0;
          }
          if (existing && quality < existing.quality) continue;
          if (moduleName === undefined) {
            // CPP template files declare placeholder module names
            // (filepath's `module System.FilePath.MODULE_NAME`); drop the
            // macro segments and attribute to the surrounding module.
            moduleName = (MODULE_RE.exec(file.text)?.[1] ?? '?')
              .split('.')
              .filter((seg) => !/^[A-Z][A-Z0-9]*_[A-Z0-9_]*$/.test(seg))
              .join('.') || '?';
          }
          const depth = moduleName.split('.').length;
          if (existing && quality === existing.quality && depth >= existing.depth) continue;
          r.candidates.set(pkg.name, {
            quality,
            depth,
            sig: fullSignature(lines, i, sig[1]),
            text,
            pkg: pkg.name,
            module: moduleName,
          });
        }
      }
    }
    log(`  harvested ${pkg.name}`);
  }

  const docPkgOrder = new Map(docPkgNames.map((name, i) => [name, i]));
  for (const [name, r] of results) {
    const entry = usage?.get(name);
    if (r.candidates.size) {
      const chosen = chooseCandidate(
        [...r.candidates.values()],
        entry?.byPkg,
        entry?.count ?? 0,
        corpusSize,
        docPkgOrder,
      );
      r.doc = { sig: chosen.sig, text: chosen.text, pkg: chosen.pkg, module: chosen.module };
    }
    delete r.candidates;

    const builtin = BUILTIN_DOCS.get(name);
    if (builtin) {
      if (!r.doc?.text) r.doc = builtin.doc;
      if (!r.fixity) r.fixity = builtin.fixity;
    }
    // Prefer the fixity declared by the package whose docs we chose.
    if (r.doc && r.fixity && r.fixity.pkg !== r.doc.pkg) {
      const fromDocPkg = r.allFixities.find((f) => f.pkg === r.doc.pkg);
      if (fromDocPkg) r.fixity = fromDocPkg;
    }
    const distinct = new Set(r.allFixities.map((f) => `${f.assoc} ${f.prec}`));
    r.fixityVaries = distinct.size > 1;
    delete r.allFixities;
  }
  return results;
}
